### ISSUE TITLE
`gridsome create` fails with "Failed to install dependencies"

### ISSUE THREAD

**Issue by dmolesUC** [gridsome/gridsome-starter-default#17]
## Steps to reproduce:

Per ["How to install"](https://gridsome.org/docs/#how-to-install):

1. `yarn global add @gridsome/cli`
2. `gridsome create my-gridsome-site`

## Expected

- Site is created

## Actual

```none
$ gridsome create my-gridsome-site
❯ Clone https://github.com/gridsome/gridsome-starter-default.git 0.7s
❯ Update project package.json 0s
❯ Install dependencies
  • Building fresh packages (4 of 4)
Error: Failed to install dependencies with yarn. Please enter my-gridsome-site directory and install dependencies with yarn or npm manually. Then run gridsome develop to start local development.

    Exit code 1
    at ChildProcess.<anonymous> (/Users/david/.nvm/versions/node/v16.1.0/lib/node_modules/@gridsome/cli/lib/commands/create.js:106:17)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

## Further observations

Attempting to follow the error message instructions by changing to the directory and running `yarn install` fails with:

```none
error /Users/david/Projects/my-gridsome-site/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/david/Projects/my-gridsome-site/node_modules/sharp
Output:
info sharp Detected globally-installed libvips v8.10.6
info sharp Building from source via node-gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.1.0 | darwin | x64
gyp info find Python using Python version 3.9.5 found at "/usr/local/opt/python@3.9/bin/python3.9"
(node:67600) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/david/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/Projects/my-gridsome-site/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/Library/Caches/node-gyp/16.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/david/Library/Caches/node-gyp/16.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/david/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/david/Library/Caches/node-gyp/16.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/david/Projects/my-gridsome-site/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package OpenEXR was not found in the pkg-config search path.
Perhaps you should add the directory containing `OpenEXR.pc'
to the PKG_CONFIG_PATH environment variable
Package 'OpenEXR', required by 'vips', not found
gyp: Call to 'PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --cflags-only-I vips-cpp vips glib-2.0 | sed s\/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/david/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/david/.nvm/versions/node/v16.1.0/bin/node" "/Users/david/.nvm/versions/node/v16.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/david/Projects/my-gridsome-site/node_modules/sharp
```

The proximate issue appears to be [lovell/sharp#2816](https://github.com/lovell/sharp/issues/2816), which in turn seems to be caused by [jamesbowman/openexrpython#44](https://github.com/jamesbowman/openexrpython/issues/44).

## System information

- OS: macOS Catalina (10.15.7)
- Node version: v16.1.0 (npm v7.11.2)
- Yarn version: v1.22.10

**Comment by dmolesUC** [comment]
Workaround, per [lovell/sharp#2729](https://github.com/lovell/sharp/issues/2729), was to temporarily unlink Homebrew `libvips`.

**Comment by dmolesUC** [comment]
Another possible workaround:

```sh
SHARP_IGNORE_GLOBAL_LIBVIPS=1 gridsome create dmoles.net
```

**Comment by dmolesUC** [comment]
…and you pretty much need to set `SHARP_IGNORE_GLOBAL_LIBVIPS` globally, because this is going to keep happening on every `yard add` or `yarn install`.
